### ISSUE TITLE
Adding status to MiddenCli to track projects

### ISSUE THREAD

**Issue by agaidinstituteadmin** [CafIncubator/Midden#113]
For the new MiddenCli, adding status to track projects will be super useful. Then in the insights researchers can actually see their performance.

**Comment by bryanrcarlson** [comment]
I think this is a great idea. I'm a little weary about schema blot since we're "limping" along with markdown + front-matter instead of a JSON file when dealing with projects. However, this one seems pretty important. Being able to sort projects by status in the Project Catalog would be extremely useful too.
